# Action name
name: Simple Test Action

# Here, this action will be enabled on all pushes.
# Modify this to fit your needs.
on:
  push

# Jobs section
jobs:
  simple-test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v4

      - name: Setup OpenHarmony SDK
        uses: openharmony-rs/setup-ohos-sdk@v0.1
        id: setup-ohos
        with:
          version: '5.0.0'

      - name: Setup Rust environment
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          target: 'aarch64-unknown-linux-ohos,armv7-unknown-linux-ohos,x86_64-unknown-linux-ohos'

      - name: Install oxk
        uses: baptiste0928/cargo-install@v3
        with:
          crate: oxk
          git: https://github.com/ohos-rs/oxc-ark.git
          tag: v0.2.1

      - name: Setup just
        uses: extractions/setup-just@v3

      - name: Build local ohrs
        run: cargo build -p ohrs

      - name: Add local ohrs to PATH
        run: echo "$PWD/target/debug" >> "$GITHUB_PATH"

      - name: Verify local ohrs
        run: ohrs --version

      - name: Cli test
        run: cargo test -p ohrs

      - name: Lint
        run: just check

      - name: Run examples
        run: just test
